 DEBUG [0x0000364c] [2018-05-27 12:02:07,188] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x0000364c] [2018-05-27 12:02:07,189] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x0000364c] [2018-05-27 12:02:07,189] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x0000364c] [2018-05-27 12:02:07,224] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x0000364c] [2018-05-27 12:02:07,254] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x0000364c] [2018-05-27 12:02:07,254] - Script::install(): KBExtra is successfully!
S_INFO [0x0000364c] [2018-05-27 12:02:07,259] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x0000364c] [2018-05-27 12:02:07,260] - TelnetServer server is running on port 34000
  INFO [0x0000364c] [2018-05-27 12:02:07,260] - ---- logger is running ----
 DEBUG [0x0000364c] [2018-05-27 12:02:07,260] - Components::process(): Request for the process of identity...
  INFO [0x0000364c] [2018-05-27 12:02:14,346] - Components::process(): Found all the components!
  INFO [0x0000364c] [2018-05-27 12:02:14,840] - ServerApp::onRegisterNewApp: uid:11365, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51224, extaddr:nonsupport, extport:0,  from 192.168.0.104:51235/0/0/0.
  INFO [0x0000364c] [2018-05-27 12:02:14,840] - Components::addComponent: reset orderLog, uid=11365!
  INFO [0x0000364c] [2018-05-27 12:02:14,841] - Components::addComponent[cellappmgr], uid=11365, componentID=6000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x0000364c] [2018-05-27 12:02:15,440] - ServerApp::onRegisterNewApp: uid:11365, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51223, extaddr:nonsupport, extport:0,  from 192.168.0.104:51236/0/0/0.
  INFO [0x0000364c] [2018-05-27 12:02:15,441] - Components::addComponent[dbmgr], uid=11365, componentID=4000, globalorderid=2, grouporderid=1, totalcount=1
 S_ERR [0x0000364c] [2018-05-27 12:02:15,461] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,463] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,463] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,465] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,466] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,468] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,471] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,480] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,482] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,484] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,486] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,488] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,490] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,491] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,492] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,493] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,494] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,495] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,496] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,497] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,498] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,499] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,500] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,501] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,502] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,503] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,504] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,505] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,506] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,506] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,507] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,508] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,509] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,510] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,511] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,512] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,513] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,514] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,515] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,516] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,517] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,518] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,519] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,520] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,520] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,521] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,522] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,523] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,524] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,525] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,526] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,527] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,528] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,529] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,530] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,531] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,532] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,533] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,534] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,534] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,535] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,536] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,537] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,538] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,539] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,540] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,541] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,542] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,543] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,544] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,545] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,545] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,546] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,547] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,548] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,549] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,550] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,551] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,552] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,553] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,554] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,555] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,556] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,557] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,558] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,559] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,560] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,561] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,562] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,563] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,563] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,565] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,565] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,566] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,567] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,568] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,569] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,570] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,571] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,572] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,573] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,574] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,575] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,576] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,577] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,578] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,579] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,580] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,581] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,582] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,583] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,584] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,585] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,585] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,586] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,588] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,588] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,589] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,590] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,591] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,592] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,593] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,594] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,595] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,596] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,597] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,598] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,599] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,600] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,601] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,602] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,603] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,604] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,605] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,606] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,607] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,608] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,609] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,610] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,611] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,612] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,613] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,614] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,614] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,615] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,615] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,616] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,616] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,617] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,617] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,618] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,618] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,619] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,619] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,620] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,620] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,621] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,622] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,622] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,623] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,623] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,624] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,624] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,625] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,625] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,626] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,627] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,627] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,628] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,628] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,629] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,629] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,630] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,630] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,631] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,631] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,632] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,632] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,633] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,634] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,634] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,635] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,635] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,636] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,636] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,637] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,637] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,638] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,638] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,639] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,640] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,640] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,641] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,641] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,642] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,642] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,643] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,643] - SystemError: error return without exception set
  WARN [0x0000364c] [2018-05-27 12:02:15,644] - e:\kbengine\kbe\src\lib\network\event_dispatcher.cpp:153: Profile callSystemTimers took 0.18 seconds
 S_ERR [0x0000364c] [2018-05-27 12:02:15,644] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,645] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,645] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,941] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,943] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,945] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,947] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,949] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,951] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,952] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,954] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,955] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,957] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,958] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,960] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,961] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,963] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,964] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,966] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,967] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,968] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,970] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,972] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,973] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,974] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,976] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,977] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,979] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,980] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,982] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,983] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,985] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,986] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,988] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,990] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,991] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,992] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,994] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:15,996] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:15,997] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:15,999] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:16,000] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:16,001] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:16,002] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:16,003] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:16,004] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:16,005] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:16,005] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:16,006] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:16,007] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:16,008] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:16,009] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:16,010] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:16,010] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:16,011] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:16,012] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:16,013] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:16,014] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:16,015] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:16,016] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:16,016] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:16,017] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:16,018] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:16,019] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:16,020] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:16,020] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:16,021] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:16,022] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:16,023] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:16,024] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:16,025] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:16,025] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:16,026] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:16,027] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:16,028] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:16,029] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:16,029] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:16,030] - SystemError: error return without exception set
  INFO [0x0000364c] [2018-05-27 12:02:16,040] - ServerApp::onRegisterNewApp: uid:11365, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51219, extaddr:nonsupport, extport:0,  from 192.168.0.104:51237/0/0/0.
  INFO [0x0000364c] [2018-05-27 12:02:16,040] - Components::addComponent[baseappmgr], uid=11365, componentID=5000, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x0000364c] [2018-05-27 12:02:16,260] - ServerApp::onRegisterNewApp: uid:11365, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51221, extaddr:nonsupport, extport:0,  from 192.168.0.104:51238/0/0/0.
  INFO [0x0000364c] [2018-05-27 12:02:16,260] - Components::addComponent[cellapp], uid=11365, componentID=8001, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x0000364c] [2018-05-27 12:02:16,360] - ServerApp::onRegisterNewApp: uid:11365, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51222, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:51239/0/0/0.
  INFO [0x0000364c] [2018-05-27 12:02:16,361] - Components::addComponent[loginapp], uid=11365, componentID=9000, globalorderid=5, grouporderid=1, totalcount=1
 S_ERR [0x0000364c] [2018-05-27 12:02:17,162] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,166] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,168] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,169] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,171] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,172] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,173] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,175] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,176] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,177] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,179] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,180] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,181] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,183] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,184] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,185] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,186] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,187] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,189] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,190] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,191] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,192] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,193] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,194] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,196] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,199] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,199] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,201] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,202] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,203] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,205] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,206] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,207] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,208] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,210] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,211] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,212] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,213] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,214] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,215] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,217] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,218] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,219] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,220] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,221] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,223] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,224] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,225] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,226] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,228] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,229] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,230] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,230] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,231] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,232] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,233] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,233] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,234] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,235] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,236] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,237] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,238] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,238] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,239] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,240] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,241] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,242] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,242] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,243] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,244] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,245] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,245] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,401] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,403] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,404] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,405] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,407] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,408] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,409] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,410] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,411] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,412] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,413] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,414] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,415] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,417] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,417] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,419] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,420] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,421] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,422] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,423] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,424] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,425] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,426] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,427] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,428] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,429] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,430] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,431] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,432] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,433] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,434] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,435] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,436] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,437] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,438] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,439] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,440] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,440] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,441] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,442] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,442] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,443] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,444] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,445] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,445] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,446] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,447] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,447] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,448] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,449] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,449] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,450] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,451] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,451] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,452] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,453] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,453] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,454] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,455] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,455] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,456] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,457] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,457] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,458] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,459] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,459] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,460] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,461] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,461] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,462] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,462] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,463] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,464] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,465] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,465] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,466] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,467] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,467] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,468] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,468] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,469] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,470] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,473] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,474] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,474] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,475] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,476] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,476] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,477] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,477] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,478] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,478] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,479] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,480] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,480] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,481] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,481] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,482] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,482] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,483] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,483] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,484] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,484] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,485] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,486] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,486] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,487] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,487] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,488] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,488] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,489] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,490] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,490] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,491] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,491] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,492] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,492] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,493] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,493] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,494] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,494] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,495] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,495] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,496] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,497] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,497] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,498] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,498] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,499] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,499] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,500] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,501] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,501] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,502] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,502] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,503] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,504] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,504] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,505] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,505] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,506] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,506] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,507] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,508] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,508] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,509] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,509] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,510] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,510] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,511] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,511] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,512] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,512] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,513] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,514] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,514] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,515] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,515] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,516] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,516] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,517] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,517] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,518] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,518] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,519] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,519] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,520] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,520] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,521] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,522] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,522] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,523] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,523] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,524] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,524] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,525] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,526] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,526] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,527] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,527] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,528] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,528] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,529] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,529] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,530] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,530] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,531] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,531] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,532] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,532] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,533] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,533] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,534] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,535] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,535] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,536] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,536] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,537] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,537] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,538] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,538] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,539] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,540] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,540] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,541] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,541] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,542] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,542] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,543] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,543] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,544] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,544] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,545] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,545] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,546] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,546] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,547] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,548] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,548] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,549] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,549] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,550] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,550] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,551] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,551] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,552] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,552] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,553] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,553] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,554] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,555] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,555] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,556] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,556] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,557] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,557] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,558] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,558] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,559] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,559] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,560] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,560] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,561] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,561] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,562] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,563] - SystemError: error return without exception set
  INFO [0x0000364c] [2018-05-27 12:02:17,780] - ServerApp::onRegisterNewApp: uid:11365, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51220, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:51240/0/0/0.
  INFO [0x0000364c] [2018-05-27 12:02:17,780] - Components::addComponent[baseapp], uid=11365, componentID=7001, globalorderid=6, grouporderid=1, totalcount=1
 S_ERR [0x0000364c] [2018-05-27 12:02:17,982] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,985] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,987] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,990] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:17,992] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:17,994] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:17,997] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,000] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,002] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,005] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,008] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,010] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,922] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,925] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,927] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,930] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,933] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,934] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,937] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,939] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,940] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,941] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,943] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,944] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,945] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,946] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,947] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,949] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,950] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,951] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,952] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,953] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,954] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,955] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,956] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,957] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,958] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,959] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,960] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,961] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,963] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,963] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,965] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,966] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,967] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,968] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,969] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,970] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,971] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,972] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,973] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,974] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,975] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,976] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,977] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,978] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,979] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,980] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,981] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,982] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,983] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,984] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,985] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,986] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,987] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,988] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,989] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,991] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,991] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,993] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,994] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,995] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,996] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:18,997] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:18,998] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:18,999] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,000] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,001] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,002] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,003] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,004] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,005] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,006] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,007] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,008] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,009] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,010] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,011] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,013] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,013] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,015] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,016] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,016] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,018] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,019] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,020] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,021] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,022] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,023] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,024] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,025] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,026] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,027] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,028] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,029] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,029] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,030] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,031] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,031] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,032] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,032] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,033] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,034] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,034] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,035] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,036] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,036] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,037] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,038] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,038] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,039] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,040] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,040] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,041] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,042] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,042] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,043] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
