  INFO [0x00002fec] [2018-05-27 11:29:31,757] - 
  INFO [0x00002fec] [2018-05-27 11:29:31,775] - -----------------------------------------------------------------------------------------


  INFO [0x00002fec] [2018-05-27 11:29:33,298] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x00002fec] [2018-05-27 11:29:33,298] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x00002fec] [2018-05-27 11:29:33,298] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x00002fec] [2018-05-27 11:29:33,699] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50628 )
  INFO [0x00002fec] [2018-05-27 11:29:33,699] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:50628, SOMAXCONN=5.
  INFO [0x00002fec] [2018-05-27 11:29:33,702] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50629 )
  INFO [0x00002fec] [2018-05-27 11:29:33,702] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50629, SOMAXCONN=5.
  INFO [0x00002fec] [2018-05-27 11:29:34,147] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 4945. PID: 8972 ----
  INFO [0x00002fec] [2018-05-27 11:29:34,148] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x00002fec] [2018-05-27 11:29:34,212] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x00002fec] [2018-05-27 11:29:34,213] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x00002fec] [2018-05-27 11:29:39,278] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x00002fec] [2018-05-27 11:29:39,372] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x00002fec] [2018-05-27 11:29:39,373] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x00002fec] [2018-05-27 11:29:39,788] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x00002fec] [2018-05-27 11:29:39,901] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x00002fec] [2018-05-27 11:29:40,065] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x00002fec] [2018-05-27 11:29:40,067] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x00002fec] [2018-05-27 11:29:40,421] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x00002fec] [2018-05-27 11:29:41,468] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x00002fec] [2018-05-27 11:29:41,468] - Script::install(): KBExtra is successfully!
S_INFO [0x00002fec] [2018-05-27 11:29:41,517] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x00002fec] [2018-05-27 11:29:41,544] - TelnetServer server is running on port 34000
  INFO [0x00002fec] [2018-05-27 11:29:41,608] - ---- logger is running ----
 DEBUG [0x00002fec] [2018-05-27 11:29:41,676] - Components::process(): Request for the process of identity...
  INFO [0x00002fec] [2018-05-27 11:29:47,893] - ServerApp::onRegisterNewApp: uid:4945, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50632, extaddr:nonsupport, extport:0,  from 192.168.0.104:50633/0/0/0.
  INFO [0x00002fec] [2018-05-27 11:29:47,893] - Components::addComponent: reset orderLog, uid=4945!
  INFO [0x00002fec] [2018-05-27 11:29:47,893] - Components::addComponent[baseappmgr], uid=4945, componentID=5000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x00002fec] [2018-05-27 11:29:47,894] - ServerApp::onRegisterNewApp: uid:4945, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50635, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:50636/0/0/0.
  INFO [0x00002fec] [2018-05-27 11:29:47,894] - Components::addComponent[loginapp], uid=4945, componentID=9000, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x00002fec] [2018-05-27 11:29:47,894] - ServerApp::onRegisterNewApp: uid:4945, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50630, extaddr:nonsupport, extport:0,  from 192.168.0.104:50637/0/0/0.
  INFO [0x00002fec] [2018-05-27 11:29:47,895] - Components::addComponent[cellappmgr], uid=4945, componentID=6000, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x00002fec] [2018-05-27 11:29:48,878] - Components::process(): Found all the components!
  INFO [0x00002fec] [2018-05-27 11:29:50,438] - ServerApp::onRegisterNewApp: uid:4945, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50638, extaddr:nonsupport, extport:0,  from 192.168.0.104:50641/0/0/0.
  INFO [0x00002fec] [2018-05-27 11:29:50,439] - Components::addComponent[cellapp], uid=4945, componentID=8001, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x00002fec] [2018-05-27 11:29:56,458] - ServerApp::onRegisterNewApp: uid:4945, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50642, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:50643/0/0/0.
  INFO [0x00002fec] [2018-05-27 11:29:56,459] - Components::addComponent[baseapp], uid=4945, componentID=7001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - 
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - -----------------------------------------------------------------------------------------


  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50647 )
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:50647, SOMAXCONN=5.
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50648 )
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50648, SOMAXCONN=5.
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 5088. PID: 5964 ----
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x00000bf4] [2018-05-27 11:30:04,654] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x00000bf4] [2018-05-27 11:30:04,654] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x00000bf4] [2018-05-27 11:30:04,654] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x00000bf4] [2018-05-27 11:30:04,654] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x00000bf4] [2018-05-27 11:30:04,654] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x00000bf4] [2018-05-27 11:30:04,654] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x00000bf4] [2018-05-27 11:30:04,654] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x00000bf4] [2018-05-27 11:30:04,654] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - Script::install(): KBExtra is successfully!
S_INFO [0x00000bf4] [2018-05-27 11:30:04,654] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - TelnetServer server is running on port 34000
  INFO [0x00000bf4] [2018-05-27 11:30:04,654] - ---- logger is running ----
 DEBUG [0x00000bf4] [2018-05-27 11:30:04,654] - Components::process(): Request for the process of identity...
  INFO [0x00000bf4] [2018-05-27 11:30:11,994] - Components::process(): Found all the components!
  INFO [0x00000bf4] [2018-05-27 11:30:12,474] - ServerApp::onRegisterNewApp: uid:5088, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50645, extaddr:nonsupport, extport:0,  from 192.168.0.104:50659/0/0/0.
  INFO [0x00000bf4] [2018-05-27 11:30:12,474] - Components::addComponent: reset orderLog, uid=5088!
  INFO [0x00000bf4] [2018-05-27 11:30:12,474] - Components::addComponent[baseappmgr], uid=5088, componentID=5000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x00000bf4] [2018-05-27 11:30:12,474] - ServerApp::onRegisterNewApp: uid:5088, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50651, extaddr:nonsupport, extport:0,  from 192.168.0.104:50660/0/0/0.
  INFO [0x00000bf4] [2018-05-27 11:30:12,474] - Components::addComponent[cellapp], uid=5088, componentID=8001, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x00000bf4] [2018-05-27 11:30:12,474] - ServerApp::onRegisterNewApp: uid:5088, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50652, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:50661/0/0/0.
  INFO [0x00000bf4] [2018-05-27 11:30:12,474] - Components::addComponent[loginapp], uid=5088, componentID=9000, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x00000bf4] [2018-05-27 11:30:13,674] - ServerApp::onRegisterNewApp: uid:5088, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50644, extaddr:nonsupport, extport:0,  from 192.168.0.104:50662/0/0/0.
  INFO [0x00000bf4] [2018-05-27 11:30:13,674] - Components::addComponent[cellappmgr], uid=5088, componentID=6000, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x00000bf4] [2018-05-27 11:30:14,493] - ServerApp::onRegisterNewApp: uid:5088, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50649, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:50663/0/0/0.
  INFO [0x00000bf4] [2018-05-27 11:30:14,493] - Components::addComponent[baseapp], uid=5088, componentID=7001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x0000318c] [2018-05-27 11:30:26,055] - 
  INFO [0x0000318c] [2018-05-27 11:30:26,063] - -----------------------------------------------------------------------------------------


  INFO [0x0000318c] [2018-05-27 11:30:26,064] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x0000318c] [2018-05-27 11:30:26,064] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x0000318c] [2018-05-27 11:30:26,064] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x0000318c] [2018-05-27 11:30:26,075] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50668 )
  INFO [0x0000318c] [2018-05-27 11:30:26,075] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:50668, SOMAXCONN=5.
  INFO [0x0000318c] [2018-05-27 11:30:26,076] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50671 )
  INFO [0x0000318c] [2018-05-27 11:30:26,077] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50671, SOMAXCONN=5.
  INFO [0x0000318c] [2018-05-27 11:30:26,080] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 5157. PID: 12620 ----
  INFO [0x0000318c] [2018-05-27 11:30:26,080] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x0000318c] [2018-05-27 11:30:26,081] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x0000318c] [2018-05-27 11:30:26,081] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x0000318c] [2018-05-27 11:30:26,212] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x0000318c] [2018-05-27 11:30:26,213] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x0000318c] [2018-05-27 11:30:26,213] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x0000318c] [2018-05-27 11:30:26,216] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x0000318c] [2018-05-27 11:30:26,217] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x0000318c] [2018-05-27 11:30:26,217] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x0000318c] [2018-05-27 11:30:26,217] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x0000318c] [2018-05-27 11:30:26,251] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x0000318c] [2018-05-27 11:30:26,281] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x0000318c] [2018-05-27 11:30:26,281] - Script::install(): KBExtra is successfully!
S_INFO [0x0000318c] [2018-05-27 11:30:26,283] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x0000318c] [2018-05-27 11:30:26,283] - TelnetServer server is running on port 34000
  INFO [0x0000318c] [2018-05-27 11:30:26,283] - ---- logger is running ----
 DEBUG [0x0000318c] [2018-05-27 11:30:26,284] - Components::process(): Request for the process of identity...
  INFO [0x0000318c] [2018-05-27 11:30:33,443] - Components::process(): Found all the components!
  INFO [0x0000318c] [2018-05-27 11:30:33,863] - ServerApp::onRegisterNewApp: uid:5157, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50667, extaddr:nonsupport, extport:0,  from 192.168.0.104:50676/0/0/0.
  INFO [0x0000318c] [2018-05-27 11:30:33,863] - Components::addComponent: reset orderLog, uid=5157!
  INFO [0x0000318c] [2018-05-27 11:30:33,864] - Components::addComponent[cellappmgr], uid=5157, componentID=6000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x0000318c] [2018-05-27 11:30:34,183] - ServerApp::onRegisterNewApp: uid:5157, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50665, extaddr:nonsupport, extport:0,  from 192.168.0.104:50677/0/0/0.
  INFO [0x0000318c] [2018-05-27 11:30:34,184] - Components::addComponent[cellapp], uid=5157, componentID=8001, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x0000318c] [2018-05-27 11:30:34,283] - ServerApp::onRegisterNewApp: uid:5157, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50670, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:50678/0/0/0.
  INFO [0x0000318c] [2018-05-27 11:30:34,284] - Components::addComponent[loginapp], uid=5157, componentID=9000, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x0000318c] [2018-05-27 11:30:35,083] - ServerApp::onRegisterNewApp: uid:5157, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50664, extaddr:nonsupport, extport:0,  from 192.168.0.104:50679/0/0/0.
  INFO [0x0000318c] [2018-05-27 11:30:35,083] - Components::addComponent[baseappmgr], uid=5157, componentID=5000, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x0000318c] [2018-05-27 11:30:35,583] - ServerApp::onRegisterNewApp: uid:5157, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50672, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:50680/0/0/0.
  INFO [0x0000318c] [2018-05-27 11:30:35,583] - Components::addComponent[baseapp], uid=5157, componentID=7001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x00003034] [2018-05-27 11:31:11,843] - 
  INFO [0x00003034] [2018-05-27 11:31:11,844] - -----------------------------------------------------------------------------------------


  INFO [0x00003034] [2018-05-27 11:31:11,844] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x00003034] [2018-05-27 11:31:11,844] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x00003034] [2018-05-27 11:31:11,844] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x00003034] [2018-05-27 11:31:11,847] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50690 )
  INFO [0x00003034] [2018-05-27 11:31:11,847] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:50690, SOMAXCONN=5.
  INFO [0x00003034] [2018-05-27 11:31:11,848] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50691 )
  INFO [0x00003034] [2018-05-27 11:31:11,849] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50691, SOMAXCONN=5.
  INFO [0x00003034] [2018-05-27 11:31:11,856] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 5307. PID: 12292 ----
  INFO [0x00003034] [2018-05-27 11:31:11,859] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x00003034] [2018-05-27 11:31:11,860] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x00003034] [2018-05-27 11:31:11,860] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x00003034] [2018-05-27 11:31:11,991] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x00003034] [2018-05-27 11:31:11,991] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x00003034] [2018-05-27 11:31:11,992] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x00003034] [2018-05-27 11:31:11,996] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x00003034] [2018-05-27 11:31:11,996] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x00003034] [2018-05-27 11:31:11,996] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x00003034] [2018-05-27 11:31:11,996] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x00003034] [2018-05-27 11:31:12,033] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x00003034] [2018-05-27 11:31:12,067] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x00003034] [2018-05-27 11:31:12,067] - Script::install(): KBExtra is successfully!
S_INFO [0x00003034] [2018-05-27 11:31:12,069] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x00003034] [2018-05-27 11:31:12,069] - TelnetServer server is running on port 34000
  INFO [0x00003034] [2018-05-27 11:31:12,070] - ---- logger is running ----
 DEBUG [0x00003034] [2018-05-27 11:31:12,070] - Components::process(): Request for the process of identity...
  INFO [0x00003034] [2018-05-27 11:31:19,190] - Components::process(): Found all the components!
  INFO [0x00003034] [2018-05-27 11:31:19,630] - ServerApp::onRegisterNewApp: uid:5307, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50695, extaddr:nonsupport, extport:0,  from 192.168.0.104:50705/0/0/0.
  INFO [0x00003034] [2018-05-27 11:31:19,631] - Components::addComponent: reset orderLog, uid=5307!
  INFO [0x00003034] [2018-05-27 11:31:19,631] - Components::addComponent[cellappmgr], uid=5307, componentID=6000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x00003034] [2018-05-27 11:31:20,150] - ServerApp::onRegisterNewApp: uid:5307, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50692, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:50706/0/0/0.
  INFO [0x00003034] [2018-05-27 11:31:20,151] - Components::addComponent[baseapp], uid=5307, componentID=7001, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x00003034] [2018-05-27 11:31:20,950] - ServerApp::onRegisterNewApp: uid:5307, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50687, extaddr:nonsupport, extport:0,  from 192.168.0.104:50708/0/0/0.
  INFO [0x00003034] [2018-05-27 11:31:20,950] - Components::addComponent[baseappmgr], uid=5307, componentID=5000, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x00003034] [2018-05-27 11:31:21,170] - ServerApp::onRegisterNewApp: uid:5307, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50693, extaddr:nonsupport, extport:0,  from 192.168.0.104:50709/0/0/0.
  INFO [0x00003034] [2018-05-27 11:31:21,171] - Components::addComponent[cellapp], uid=5307, componentID=8001, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x00003034] [2018-05-27 11:31:21,289] - ServerApp::onRegisterNewApp: uid:5307, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50694, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:50710/0/0/0.
  INFO [0x00003034] [2018-05-27 11:31:21,289] - Components::addComponent[loginapp], uid=5307, componentID=9000, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x00003034] [2018-05-27 11:31:25,009] - ServerApp::onRegisterNewApp: uid:5307, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50688, extaddr:nonsupport, extport:0,  from 192.168.0.104:50713/0/0/0.
  INFO [0x00003034] [2018-05-27 11:31:25,010] - Components::addComponent[dbmgr], uid=5307, componentID=4000, globalorderid=6, grouporderid=1, totalcount=1
  INFO [0x00003034] [2018-05-27 11:31:31,131] - Logger::registerLogWatcher: addr=192.168.0.104:50733 is successfully!
  INFO [0x00002a20] [2018-05-27 11:32:37,646] - 
  INFO [0x00002a20] [2018-05-27 11:32:37,647] - -----------------------------------------------------------------------------------------


  INFO [0x00002a20] [2018-05-27 11:32:37,647] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x00002a20] [2018-05-27 11:32:37,647] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x00002a20] [2018-05-27 11:32:37,647] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x00002a20] [2018-05-27 11:32:37,656] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50742 )
  INFO [0x00002a20] [2018-05-27 11:32:37,656] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:50742, SOMAXCONN=5.
  INFO [0x00002a20] [2018-05-27 11:32:37,657] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50743 )
  INFO [0x00002a20] [2018-05-27 11:32:37,658] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50743, SOMAXCONN=5.
  INFO [0x00002a20] [2018-05-27 11:32:37,661] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 5588. PID: 2800 ----
  INFO [0x00002a20] [2018-05-27 11:32:37,665] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x00002a20] [2018-05-27 11:32:37,668] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x00002a20] [2018-05-27 11:32:37,669] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x00002a20] [2018-05-27 11:32:37,807] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x00002a20] [2018-05-27 11:32:37,807] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x00002a20] [2018-05-27 11:32:37,808] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x00002a20] [2018-05-27 11:32:37,812] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x00002a20] [2018-05-27 11:32:37,812] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x00002a20] [2018-05-27 11:32:37,812] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x00002a20] [2018-05-27 11:32:37,813] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x00002a20] [2018-05-27 11:32:37,848] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x00002a20] [2018-05-27 11:32:37,891] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x00002a20] [2018-05-27 11:32:37,891] - Script::install(): KBExtra is successfully!
S_INFO [0x00002a20] [2018-05-27 11:32:37,894] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x00002a20] [2018-05-27 11:32:37,894] - TelnetServer server is running on port 34000
  INFO [0x00002a20] [2018-05-27 11:32:37,895] - ---- logger is running ----
 DEBUG [0x00002a20] [2018-05-27 11:32:37,895] - Components::process(): Request for the process of identity...
  INFO [0x00002a20] [2018-05-27 11:32:45,015] - Components::process(): Found all the components!
  INFO [0x00002a20] [2018-05-27 11:32:45,115] - Logger::registerLogWatcher: addr=192.168.0.104:50764 is successfully!
  INFO [0x00002a20] [2018-05-27 11:32:45,595] - ServerApp::onRegisterNewApp: uid:5588, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50746, extaddr:nonsupport, extport:0,  from 192.168.0.104:50766/0/0/0.
  INFO [0x00002a20] [2018-05-27 11:32:45,595] - Components::addComponent: reset orderLog, uid=5588!
  INFO [0x00002a20] [2018-05-27 11:32:45,595] - Components::addComponent[cellappmgr], uid=5588, componentID=6000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x00002a20] [2018-05-27 11:32:45,795] - ServerApp::onRegisterNewApp: uid:5588, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50745, extaddr:nonsupport, extport:0,  from 192.168.0.104:50768/0/0/0.
  INFO [0x00002a20] [2018-05-27 11:32:45,795] - Components::addComponent[cellapp], uid=5588, componentID=8001, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x00002a20] [2018-05-27 11:32:45,895] - ServerApp::onRegisterNewApp: uid:5588, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50747, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:50769/0/0/0.
  INFO [0x00002a20] [2018-05-27 11:32:45,895] - Components::addComponent[loginapp], uid=5588, componentID=9000, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x00002a20] [2018-05-27 11:32:46,720] - ServerApp::onRegisterNewApp: uid:5588, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50744, extaddr:nonsupport, extport:0,  from 192.168.0.104:50772/0/0/0.
  INFO [0x00002a20] [2018-05-27 11:32:46,721] - Components::addComponent[baseappmgr], uid=5588, componentID=5000, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x00002a20] [2018-05-27 11:32:47,115] - ServerApp::onRegisterNewApp: uid:5588, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50748, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:50775/0/0/0.
  INFO [0x00002a20] [2018-05-27 11:32:47,115] - Components::addComponent[baseapp], uid=5588, componentID=7001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x00002a20] [2018-05-27 11:32:47,315] - ServerApp::onRegisterNewApp: uid:5588, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50741, extaddr:nonsupport, extport:0,  from 192.168.0.104:50779/0/0/0.
  INFO [0x00002a20] [2018-05-27 11:32:47,315] - Components::addComponent[dbmgr], uid=5588, componentID=4000, globalorderid=6, grouporderid=1, totalcount=1
  INFO [0x0000133c] [2018-05-27 11:34:44,303] - 
  INFO [0x0000133c] [2018-05-27 11:34:44,304] - -----------------------------------------------------------------------------------------


  INFO [0x0000133c] [2018-05-27 11:34:44,304] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x0000133c] [2018-05-27 11:34:44,304] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x0000133c] [2018-05-27 11:34:44,304] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x0000133c] [2018-05-27 11:34:44,319] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50809 )
  INFO [0x0000133c] [2018-05-27 11:34:44,319] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:50809, SOMAXCONN=5.
  INFO [0x0000133c] [2018-05-27 11:34:44,320] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50810 )
  INFO [0x0000133c] [2018-05-27 11:34:44,320] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50810, SOMAXCONN=5.
  INFO [0x0000133c] [2018-05-27 11:34:44,323] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 5999. PID: 7396 ----
  INFO [0x0000133c] [2018-05-27 11:34:44,329] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x0000133c] [2018-05-27 11:34:44,330] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x0000133c] [2018-05-27 11:34:44,330] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x0000133c] [2018-05-27 11:34:44,460] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x0000133c] [2018-05-27 11:34:44,460] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x0000133c] [2018-05-27 11:34:44,461] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x0000133c] [2018-05-27 11:34:44,464] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x0000133c] [2018-05-27 11:34:44,464] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x0000133c] [2018-05-27 11:34:44,464] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x0000133c] [2018-05-27 11:34:44,465] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x0000133c] [2018-05-27 11:34:44,508] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x0000133c] [2018-05-27 11:34:44,549] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x0000133c] [2018-05-27 11:34:44,549] - Script::install(): KBExtra is successfully!
S_INFO [0x0000133c] [2018-05-27 11:34:44,552] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x0000133c] [2018-05-27 11:34:44,552] - TelnetServer server is running on port 34000
  INFO [0x0000133c] [2018-05-27 11:34:44,552] - ---- logger is running ----
 DEBUG [0x0000133c] [2018-05-27 11:34:44,552] - Components::process(): Request for the process of identity...
  INFO [0x0000133c] [2018-05-27 11:34:51,672] - Components::process(): Found all the components!
  INFO [0x0000133c] [2018-05-27 11:34:52,172] - ServerApp::onRegisterNewApp: uid:5999, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50815, extaddr:nonsupport, extport:0,  from 192.168.0.104:50832/0/0/0.
  INFO [0x0000133c] [2018-05-27 11:34:52,172] - Components::addComponent: reset orderLog, uid=5999!
  INFO [0x0000133c] [2018-05-27 11:34:52,172] - Components::addComponent[baseappmgr], uid=5999, componentID=5000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x0000133c] [2018-05-27 11:34:52,173] - ServerApp::onRegisterNewApp: uid:5999, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50816, extaddr:nonsupport, extport:0,  from 192.168.0.104:50833/0/0/0.
  INFO [0x0000133c] [2018-05-27 11:34:52,173] - Components::addComponent[cellappmgr], uid=5999, componentID=6000, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x0000133c] [2018-05-27 11:34:52,472] - Logger::registerLogWatcher: addr=192.168.0.104:50834 is successfully!
  INFO [0x0000133c] [2018-05-27 11:34:52,492] - ServerApp::onRegisterNewApp: uid:5999, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50812, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:50835/0/0/0.
  INFO [0x0000133c] [2018-05-27 11:34:52,492] - Components::addComponent[loginapp], uid=5999, componentID=9000, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x0000133c] [2018-05-27 11:34:53,601] - ServerApp::onRegisterNewApp: uid:5999, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50811, extaddr:nonsupport, extport:0,  from 192.168.0.104:50839/0/0/0.
  INFO [0x0000133c] [2018-05-27 11:34:53,601] - Components::addComponent[cellapp], uid=5999, componentID=8001, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x0000133c] [2018-05-27 11:34:53,792] - ServerApp::onRegisterNewApp: uid:5999, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50814, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:50842/0/0/0.
  INFO [0x0000133c] [2018-05-27 11:34:53,792] - Components::addComponent[baseapp], uid=5999, componentID=7001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x0000133c] [2018-05-27 11:34:54,012] - ServerApp::onRegisterNewApp: uid:5999, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50813, extaddr:nonsupport, extport:0,  from 192.168.0.104:50847/0/0/0.
  INFO [0x0000133c] [2018-05-27 11:34:54,013] - Components::addComponent[dbmgr], uid=5999, componentID=4000, globalorderid=6, grouporderid=1, totalcount=1
  INFO [0x000032dc] [2018-05-27 11:55:00,424] - 
  INFO [0x000032dc] [2018-05-27 11:55:00,426] - -----------------------------------------------------------------------------------------


  INFO [0x000032dc] [2018-05-27 11:55:00,427] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x000032dc] [2018-05-27 11:55:00,427] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x000032dc] [2018-05-27 11:55:00,427] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x000032dc] [2018-05-27 11:55:00,444] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50958 )
  INFO [0x000032dc] [2018-05-27 11:55:00,444] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:50958, SOMAXCONN=5.
  INFO [0x000032dc] [2018-05-27 11:55:00,445] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50960 )
  INFO [0x000032dc] [2018-05-27 11:55:00,445] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50960, SOMAXCONN=5.
  INFO [0x000032dc] [2018-05-27 11:55:00,449] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 9974. PID: 11184 ----
  INFO [0x000032dc] [2018-05-27 11:55:00,456] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x000032dc] [2018-05-27 11:55:00,456] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x000032dc] [2018-05-27 11:55:00,457] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x000032dc] [2018-05-27 11:55:00,584] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x000032dc] [2018-05-27 11:55:00,585] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x000032dc] [2018-05-27 11:55:00,585] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x000032dc] [2018-05-27 11:55:00,588] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x000032dc] [2018-05-27 11:55:00,588] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x000032dc] [2018-05-27 11:55:00,588] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x000032dc] [2018-05-27 11:55:00,589] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x000032dc] [2018-05-27 11:55:00,620] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x000032dc] [2018-05-27 11:55:00,652] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x000032dc] [2018-05-27 11:55:00,652] - Script::install(): KBExtra is successfully!
S_INFO [0x000032dc] [2018-05-27 11:55:00,654] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x000032dc] [2018-05-27 11:55:00,655] - TelnetServer server is running on port 34000
  INFO [0x000032dc] [2018-05-27 11:55:00,655] - ---- logger is running ----
 DEBUG [0x000032dc] [2018-05-27 11:55:00,655] - Components::process(): Request for the process of identity...
  INFO [0x000032dc] [2018-05-27 11:55:06,756] - Logger::registerLogWatcher: addr=192.168.0.104:50982 is successfully!
  INFO [0x000032dc] [2018-05-27 11:55:07,776] - Components::process(): Found all the components!
  INFO [0x000032dc] [2018-05-27 11:55:08,376] - ServerApp::onRegisterNewApp: uid:9974, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50964, extaddr:nonsupport, extport:0,  from 192.168.0.104:50988/0/0/0.
  INFO [0x000032dc] [2018-05-27 11:55:08,377] - Components::addComponent: reset orderLog, uid=9974!
  INFO [0x000032dc] [2018-05-27 11:55:08,378] - Components::addComponent[cellappmgr], uid=9974, componentID=6000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x000032dc] [2018-05-27 11:55:08,496] - ServerApp::onRegisterNewApp: uid:9974, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50965, extaddr:nonsupport, extport:0,  from 192.168.0.104:50989/0/0/0.
  INFO [0x000032dc] [2018-05-27 11:55:08,497] - Components::addComponent[cellapp], uid=9974, componentID=8001, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x000032dc] [2018-05-27 11:55:09,507] - ServerApp::onRegisterNewApp: uid:9974, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50963, extaddr:nonsupport, extport:0,  from 192.168.0.104:50991/0/0/0.
  INFO [0x000032dc] [2018-05-27 11:55:09,507] - Components::addComponent[baseappmgr], uid=9974, componentID=5000, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x000032dc] [2018-05-27 11:55:09,896] - ServerApp::onRegisterNewApp: uid:9974, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50961, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:50992/0/0/0.
  INFO [0x000032dc] [2018-05-27 11:55:09,896] - Components::addComponent[loginapp], uid=9974, componentID=9000, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x000032dc] [2018-05-27 11:55:09,896] - ServerApp::onRegisterNewApp: uid:9974, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50962, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:50993/0/0/0.
  INFO [0x000032dc] [2018-05-27 11:55:09,897] - Components::addComponent[baseapp], uid=9974, componentID=7001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x000032dc] [2018-05-27 11:55:10,216] - ServerApp::onRegisterNewApp: uid:9974, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:50966, extaddr:nonsupport, extport:0,  from 192.168.0.104:50994/0/0/0.
  INFO [0x000032dc] [2018-05-27 11:55:10,216] - Components::addComponent[dbmgr], uid=9974, componentID=4000, globalorderid=6, grouporderid=1, totalcount=1
  INFO [0x00002e5c] [2018-05-27 11:57:20,149] - 
  INFO [0x00002e5c] [2018-05-27 11:57:20,151] - -----------------------------------------------------------------------------------------


  INFO [0x00002e5c] [2018-05-27 11:57:20,152] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x00002e5c] [2018-05-27 11:57:20,152] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x00002e5c] [2018-05-27 11:57:20,152] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x00002e5c] [2018-05-27 11:57:20,159] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51060 )
  INFO [0x00002e5c] [2018-05-27 11:57:20,159] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:51060, SOMAXCONN=5.
  INFO [0x00002e5c] [2018-05-27 11:57:20,161] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51061 )
  INFO [0x00002e5c] [2018-05-27 11:57:20,161] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51061, SOMAXCONN=5.
  INFO [0x00002e5c] [2018-05-27 11:57:20,165] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 10428. PID: 10320 ----
  INFO [0x00002e5c] [2018-05-27 11:57:20,169] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x00002e5c] [2018-05-27 11:57:20,170] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x00002e5c] [2018-05-27 11:57:20,170] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x00002e5c] [2018-05-27 11:57:20,297] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x00002e5c] [2018-05-27 11:57:20,298] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x00002e5c] [2018-05-27 11:57:20,298] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x00002e5c] [2018-05-27 11:57:20,301] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x00002e5c] [2018-05-27 11:57:20,301] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x00002e5c] [2018-05-27 11:57:20,301] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x00002e5c] [2018-05-27 11:57:20,302] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x00002e5c] [2018-05-27 11:57:20,337] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x00002e5c] [2018-05-27 11:57:20,375] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x00002e5c] [2018-05-27 11:57:20,375] - Script::install(): KBExtra is successfully!
S_INFO [0x00002e5c] [2018-05-27 11:57:20,378] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x00002e5c] [2018-05-27 11:57:20,378] - TelnetServer server is running on port 34000
  INFO [0x00002e5c] [2018-05-27 11:57:20,378] - ---- logger is running ----
 DEBUG [0x00002e5c] [2018-05-27 11:57:20,379] - Components::process(): Request for the process of identity...
  INFO [0x00002e5c] [2018-05-27 11:57:27,519] - Components::process(): Found all the components!
  INFO [0x00002e5c] [2018-05-27 11:57:28,059] - ServerApp::onRegisterNewApp: uid:10428, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51064, extaddr:nonsupport, extport:0,  from 192.168.0.104:51081/0/0/0.
  INFO [0x00002e5c] [2018-05-27 11:57:28,060] - Components::addComponent: reset orderLog, uid=10428!
  INFO [0x00002e5c] [2018-05-27 11:57:28,061] - Components::addComponent[cellappmgr], uid=10428, componentID=6000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x00002e5c] [2018-05-27 11:57:28,179] - ServerApp::onRegisterNewApp: uid:10428, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51059, extaddr:nonsupport, extport:0,  from 192.168.0.104:51082/0/0/0.
  INFO [0x00002e5c] [2018-05-27 11:57:28,180] - Components::addComponent[cellapp], uid=10428, componentID=8001, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x00002e5c] [2018-05-27 11:57:28,299] - ServerApp::onRegisterNewApp: uid:10428, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51062, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:51083/0/0/0.
  INFO [0x00002e5c] [2018-05-27 11:57:28,299] - Components::addComponent[loginapp], uid=10428, componentID=9000, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x00002e5c] [2018-05-27 11:57:29,219] - ServerApp::onRegisterNewApp: uid:10428, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51058, extaddr:nonsupport, extport:0,  from 192.168.0.104:51084/0/0/0.
  INFO [0x00002e5c] [2018-05-27 11:57:29,219] - Components::addComponent[baseappmgr], uid=10428, componentID=5000, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x00002e5c] [2018-05-27 11:57:29,599] - ServerApp::onRegisterNewApp: uid:10428, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51065, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:51087/0/0/0.
  INFO [0x00002e5c] [2018-05-27 11:57:29,600] - Components::addComponent[baseapp], uid=10428, componentID=7001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x00002e5c] [2018-05-27 11:57:29,919] - ServerApp::onRegisterNewApp: uid:10428, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51063, extaddr:nonsupport, extport:0,  from 192.168.0.104:51091/0/0/0.
  INFO [0x00002e5c] [2018-05-27 11:57:29,919] - Components::addComponent[dbmgr], uid=10428, componentID=4000, globalorderid=6, grouporderid=1, totalcount=1
  INFO [0x00002e5c] [2018-05-27 11:57:31,859] - Logger::registerLogWatcher: addr=192.168.0.104:51095 is successfully!
  INFO [0x00002e84] [2018-05-27 12:00:38,910] - 
  INFO [0x00002e84] [2018-05-27 12:00:38,914] - -----------------------------------------------------------------------------------------


  INFO [0x00002e84] [2018-05-27 12:00:38,915] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x00002e84] [2018-05-27 12:00:38,915] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x00002e84] [2018-05-27 12:00:38,915] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x00002e84] [2018-05-27 12:00:38,919] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51146 )
  INFO [0x00002e84] [2018-05-27 12:00:38,920] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:51146, SOMAXCONN=5.
  INFO [0x00002e84] [2018-05-27 12:00:38,922] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51147 )
  INFO [0x00002e84] [2018-05-27 12:00:38,922] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51147, SOMAXCONN=5.
  INFO [0x00002e84] [2018-05-27 12:00:38,926] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 11077. PID: 13452 ----
  INFO [0x00002e84] [2018-05-27 12:00:38,928] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x00002e84] [2018-05-27 12:00:38,928] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x00002e84] [2018-05-27 12:00:38,928] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x00002e84] [2018-05-27 12:00:39,060] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x00002e84] [2018-05-27 12:00:39,060] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x00002e84] [2018-05-27 12:00:39,061] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x00002e84] [2018-05-27 12:00:39,064] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x00002e84] [2018-05-27 12:00:39,064] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x00002e84] [2018-05-27 12:00:39,064] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x00002e84] [2018-05-27 12:00:39,064] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x00002e84] [2018-05-27 12:00:39,104] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x00002e84] [2018-05-27 12:00:39,142] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x00002e84] [2018-05-27 12:00:39,142] - Script::install(): KBExtra is successfully!
S_INFO [0x00002e84] [2018-05-27 12:00:39,161] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x00002e84] [2018-05-27 12:00:39,162] - TelnetServer server is running on port 34000
  INFO [0x00002e84] [2018-05-27 12:00:39,162] - ---- logger is running ----
 DEBUG [0x00002e84] [2018-05-27 12:00:39,162] - Components::process(): Request for the process of identity...
  INFO [0x00002e84] [2018-05-27 12:00:46,317] - Components::process(): Found all the components!
  INFO [0x00002e84] [2018-05-27 12:00:46,762] - ServerApp::onRegisterNewApp: uid:11077, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51153, extaddr:nonsupport, extport:0,  from 192.168.0.104:51165/0/0/0.
  INFO [0x00002e84] [2018-05-27 12:00:46,762] - Components::addComponent: reset orderLog, uid=11077!
  INFO [0x00002e84] [2018-05-27 12:00:46,762] - Components::addComponent[baseappmgr], uid=11077, componentID=5000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x00002e84] [2018-05-27 12:00:46,962] - ServerApp::onRegisterNewApp: uid:11077, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51151, extaddr:nonsupport, extport:0,  from 192.168.0.104:51166/0/0/0.
  INFO [0x00002e84] [2018-05-27 12:00:46,962] - Components::addComponent[cellapp], uid=11077, componentID=8001, globalorderid=2, grouporderid=1, totalcount=1
 S_ERR [0x00002e84] [2018-05-27 12:00:47,863] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,886] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,887] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,889] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,890] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,890] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,891] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,892] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,893] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,894] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,894] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,895] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,896] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,897] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,897] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,898] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,899] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,899] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,900] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,901] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,901] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,902] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,903] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,903] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,904] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,904] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,905] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,905] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,906] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,907] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,908] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,908] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,909] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,910] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,910] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,911] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,912] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,912] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,913] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,914] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,915] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,915] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,916] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,917] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,917] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,918] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,919] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,919] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,920] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,921] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,921] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,922] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,923] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,923] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,924] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,925] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,925] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,926] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,927] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,928] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,928] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,929] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,930] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,931] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,932] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,932] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,933] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,934] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,934] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,935] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,936] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,937] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:47,938] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:47,938] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:47,939] - SystemError: error return without exception set
  INFO [0x00002e84] [2018-05-27 12:00:47,962] - ServerApp::onRegisterNewApp: uid:11077, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51150, extaddr:nonsupport, extport:0,  from 192.168.0.104:51167/0/0/0.
  INFO [0x00002e84] [2018-05-27 12:00:47,962] - Components::addComponent[cellappmgr], uid=11077, componentID=6000, globalorderid=3, grouporderid=1, totalcount=1
 S_ERR [0x00002e84] [2018-05-27 12:00:48,103] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,105] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,106] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,108] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,109] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,109] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,111] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,112] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,113] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,114] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,115] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,116] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,117] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,118] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,118] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,120] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,121] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,122] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,123] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,124] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,125] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,126] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,127] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,128] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,129] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,130] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,131] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,132] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,133] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,133] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,134] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,136] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,136] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,137] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,139] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,139] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,141] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,142] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,142] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,143] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,145] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,145] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,146] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,147] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,148] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,149] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,151] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,151] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,152] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,153] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,154] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,155] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,157] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,157] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,158] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,159] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,160] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,161] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,163] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,163] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,164] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,166] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,166] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,167] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,169] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,169] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,170] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,171] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,172] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,173] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,174] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,174] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,175] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,176] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,176] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,177] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,178] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,179] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,180] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,181] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,181] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,182] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,183] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,184] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,185] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,186] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,186] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,187] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,188] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,189] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,189] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,190] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,190] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,191] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,191] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,192] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,192] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,193] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,193] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,194] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,194] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,194] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,195] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,195] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,196] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,196] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,197] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,197] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,198] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,198] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,198] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,199] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,199] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,200] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,200] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,201] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,201] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,202] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,202] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,202] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,203] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,204] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,204] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,204] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,205] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,205] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,206] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,206] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,207] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,207] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,208] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,208] - SystemError: error return without exception set
  WARN [0x00002e84] [2018-05-27 12:00:48,208] - e:\kbengine\kbe\src\lib\network\event_dispatcher.cpp:153: Profile callSystemTimers took 0.11 seconds
  INFO [0x00002e84] [2018-05-27 12:00:48,282] - ServerApp::onRegisterNewApp: uid:11077, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51149, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:51168/0/0/0.
  INFO [0x00002e84] [2018-05-27 12:00:48,282] - Components::addComponent[loginapp], uid=11077, componentID=9000, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x00002e84] [2018-05-27 12:00:48,382] - ServerApp::onRegisterNewApp: uid:11077, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51154, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:51169/0/0/0.
  INFO [0x00002e84] [2018-05-27 12:00:48,382] - Components::addComponent[baseapp], uid=11077, componentID=7001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x00002e84] [2018-05-27 12:00:48,702] - ServerApp::onRegisterNewApp: uid:11077, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51152, extaddr:nonsupport, extport:0,  from 192.168.0.104:51170/0/0/0.
  INFO [0x00002e84] [2018-05-27 12:00:48,702] - Components::addComponent[dbmgr], uid=11077, componentID=4000, globalorderid=6, grouporderid=1, totalcount=1
 S_ERR [0x00002e84] [2018-05-27 12:00:48,723] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,725] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,726] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,727] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,729] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,729] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,731] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,733] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,734] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,735] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,737] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,738] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,740] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,741] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,742] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,743] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,745] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,745] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,747] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,748] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,748] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,750] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,751] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,752] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,753] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,754] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,755] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,756] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,758] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,758] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,760] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,761] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,762] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,763] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,764] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,765] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,767] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,768] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,769] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,770] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,771] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,772] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,774] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,775] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,775] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,777] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,779] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,780] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,782] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,783] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,784] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,786] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,787] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,788] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,789] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,790] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,790] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,791] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,792] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,792] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,793] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,794] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,794] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,795] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,796] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,796] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,797] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,798] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,798] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,799] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,800] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,800] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,801] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,801] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,802] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,803] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,803] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,804] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,805] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,806] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,806] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,807] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,808] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,808] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,809] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,810] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,810] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,811] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,811] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,812] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,813] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,813] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,814] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,815] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,815] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,816] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,816] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,817] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,817] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,818] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,819] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,819] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,820] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,820] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,820] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,821] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,821] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,822] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,822] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,822] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,823] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,823] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,824] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,824] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,825] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,825] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,825] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,826] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,826] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,826] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,827] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,827] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,827] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,828] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,828] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,828] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,829] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,829] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,829] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,830] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,830] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,831] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,831] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,832] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,832] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,832] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,833] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,833] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,834] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,834] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,834] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,835] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,835] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,835] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,836] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,836] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,836] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,837] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,837] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,837] - SystemError: error return without exception set
 S_ERR [0x00002e84] [2018-05-27 12:00:48,838] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x00002e84] [2018-05-27 12:00:48,838] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x00002e84] [2018-05-27 12:00:48,838] - SystemError: error return without exception set
