 S_ERR [0x0000364c] [2018-05-27 12:02:19,044] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,045] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,046] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,047] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,048] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,048] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,049] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,050] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,050] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,051] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,052] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,052] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,053] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,054] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,054] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,055] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,055] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,056] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,057] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,058] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,058] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,059] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,059] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,060] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,061] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,061] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,062] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,063] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,063] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,064] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,065] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,065] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,066] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,066] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,067] - SystemError: error return without exception set
  WARN [0x0000364c] [2018-05-27 12:02:19,067] - e:\kbengine\kbe\src\lib\network\event_dispatcher.cpp:153: Profile callSystemTimers took 0.15 seconds
 S_ERR [0x0000364c] [2018-05-27 12:02:19,068] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,069] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,069] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,070] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,070] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,071] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,141] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,145] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,147] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,150] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,153] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,155] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,157] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,160] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,162] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,165] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,168] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,170] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,181] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,184] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,187] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,189] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,192] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,194] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,197] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,200] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,201] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,204] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,207] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,208] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,221] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,222] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,224] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,502] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,505] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,507] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,509] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,512] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,514] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,517] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,519] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,521] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,523] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,526] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,528] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,530] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,532] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,535] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,537] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,540] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,542] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,544] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,547] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,549] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,551] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,553] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,555] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:19,557] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:19,559] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:19,560] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:20,321] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:20,322] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:20,323] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:20,324] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:20,325] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:20,326] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:20,327] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:20,328] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:20,329] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:20,341] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:20,342] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:20,343] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:20,345] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:20,346] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:20,347] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:20,348] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:20,350] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:20,350] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:20,621] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:20,623] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:20,624] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:20,626] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:20,627] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:20,628] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:20,630] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:20,632] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:20,633] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:20,634] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:20,636] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:20,637] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:20,639] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:20,640] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:20,642] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:20,643] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:20,645] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:20,646] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:20,647] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:20,648] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:20,649] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:21,022] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:21,024] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:21,025] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:21,028] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:21,030] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:21,031] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:21,033] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:21,035] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:21,036] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:21,038] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:21,039] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:21,040] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:21,041] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:21,042] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:21,042] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:21,521] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:21,523] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:21,524] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:21,527] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:21,529] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:21,530] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:21,532] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:21,534] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:21,535] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:21,538] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:21,540] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:21,541] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:21,543] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:21,545] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:21,546] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:22,641] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:22,644] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:22,645] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:22,648] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:22,650] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:22,651] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:22,654] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:22,657] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:22,658] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:22,660] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:22,663] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:22,664] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:22,700] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:22,702] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:22,703] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:22,706] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:22,708] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:22,709] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:22,720] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:22,722] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:22,723] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:22,725] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:22,727] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:22,728] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:22,740] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:22,742] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:22,743] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:22,800] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:22,803] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:22,804] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:22,806] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:22,809] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:22,810] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:23,120] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:23,123] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:23,124] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:23,125] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:23,127] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:23,129] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:23,131] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:23,133] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:23,133] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:23,135] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:23,137] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:23,138] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:23,140] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:23,142] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:23,143] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,262] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,264] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,266] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,268] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,271] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,272] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,322] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,323] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,324] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,327] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,329] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,330] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,341] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,343] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,344] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,346] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,347] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,348] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,351] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,352] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,353] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,355] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,357] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,358] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,361] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,363] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,364] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,366] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,367] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,368] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,369] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,370] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,371] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,400] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,401] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,402] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,403] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,403] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,404] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,461] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,462] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,463] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,464] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,466] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,466] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:24,468] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:24,469] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:24,470] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:27,340] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:27,342] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:27,342] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:27,343] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:27,344] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:27,344] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:27,345] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:27,346] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:27,347] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,520] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,521] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,522] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,522] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,523] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,523] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,524] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,525] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,525] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,526] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,526] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,527] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,527] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,528] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,528] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,529] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,529] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,530] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,530] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,531] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,531] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,532] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,532] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,533] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,533] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,534] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,534] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,535] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,535] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,536] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,536] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,537] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,537] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,538] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,538] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,539] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,539] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,540] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,540] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,541] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,541] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,541] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,542] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,543] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,543] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,543] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,544] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,544] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,600] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,601] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,602] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,800] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,801] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,801] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,802] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,802] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,803] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,803] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,804] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,804] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:28,805] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:28,805] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:28,805] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:29,062] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:29,064] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:29,066] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:29,141] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:29,143] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:29,143] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:29,161] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:29,162] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:29,164] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:29,165] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:29,167] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:29,168] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:29,169] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:29,170] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:29,171] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:29,201] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:29,204] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:29,205] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:29,222] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:29,224] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:29,225] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:29,228] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:29,230] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:29,231] - SystemError: error return without exception set
 S_ERR [0x0000364c] [2018-05-27 12:02:29,234] - FileNotFoundError: [Errno 2] No such file or directory: 'mylog/mylog.log'
 S_ERR [0x0000364c] [2018-05-27 12:02:29,236] - Traceback (most recent call last):
  File "E:/kbengine/assets/scripts/logger\kbemain.py", line 43, in onLogWrote
    f=KBEngine.open(path,'ab')
 S_ERR [0x0000364c] [2018-05-27 12:02:29,238] - SystemError: error return without exception set
  INFO [0x00003430] [2018-05-27 12:02:57,378] - 
  INFO [0x00003430] [2018-05-27 12:02:57,378] - -----------------------------------------------------------------------------------------


  INFO [0x00003430] [2018-05-27 12:02:57,379] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x00003430] [2018-05-27 12:02:57,379] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x00003430] [2018-05-27 12:02:57,379] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x00003430] [2018-05-27 12:02:57,385] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51257 )
  INFO [0x00003430] [2018-05-27 12:02:57,386] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:51257, SOMAXCONN=5.
  INFO [0x00003430] [2018-05-27 12:02:57,387] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51258 )
  INFO [0x00003430] [2018-05-27 12:02:57,387] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51258, SOMAXCONN=5.
  INFO [0x00003430] [2018-05-27 12:02:57,391] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 11528. PID: 2704 ----
  INFO [0x00003430] [2018-05-27 12:02:57,392] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x00003430] [2018-05-27 12:02:57,392] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x00003430] [2018-05-27 12:02:57,392] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x00003430] [2018-05-27 12:02:57,518] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x00003430] [2018-05-27 12:02:57,519] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x00003430] [2018-05-27 12:02:57,519] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x00003430] [2018-05-27 12:02:57,524] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x00003430] [2018-05-27 12:02:57,524] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x00003430] [2018-05-27 12:02:57,524] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x00003430] [2018-05-27 12:02:57,524] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x00003430] [2018-05-27 12:02:57,555] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x00003430] [2018-05-27 12:02:57,587] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x00003430] [2018-05-27 12:02:57,587] - Script::install(): KBExtra is successfully!
S_INFO [0x00003430] [2018-05-27 12:02:57,589] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x00003430] [2018-05-27 12:02:57,589] - TelnetServer server is running on port 34000
  INFO [0x00003430] [2018-05-27 12:02:57,590] - ---- logger is running ----
 DEBUG [0x00003430] [2018-05-27 12:02:57,590] - Components::process(): Request for the process of identity...
  INFO [0x000039e0] [2018-05-27 12:03:02,078] - 
  INFO [0x000039e0] [2018-05-27 12:03:02,100] - -----------------------------------------------------------------------------------------


  INFO [0x000039e0] [2018-05-27 12:03:02,101] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x000039e0] [2018-05-27 12:03:02,101] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x000039e0] [2018-05-27 12:03:02,101] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x000039e0] [2018-05-27 12:03:02,114] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51274 )
  INFO [0x000039e0] [2018-05-27 12:03:02,114] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:51274, SOMAXCONN=5.
  INFO [0x000039e0] [2018-05-27 12:03:02,116] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51278 )
  INFO [0x000039e0] [2018-05-27 12:03:02,116] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51278, SOMAXCONN=5.
  INFO [0x000039e0] [2018-05-27 12:03:02,120] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 11544. PID: 14812 ----
  INFO [0x000039e0] [2018-05-27 12:03:02,120] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x000039e0] [2018-05-27 12:03:02,120] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x000039e0] [2018-05-27 12:03:02,120] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x000039e0] [2018-05-27 12:03:02,255] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x000039e0] [2018-05-27 12:03:02,255] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x000039e0] [2018-05-27 12:03:02,256] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x000039e0] [2018-05-27 12:03:02,260] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x000039e0] [2018-05-27 12:03:02,260] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x000039e0] [2018-05-27 12:03:02,260] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x000039e0] [2018-05-27 12:03:02,261] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x000039e0] [2018-05-27 12:03:02,294] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x000039e0] [2018-05-27 12:03:02,326] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x000039e0] [2018-05-27 12:03:02,326] - Script::install(): KBExtra is successfully!
S_INFO [0x000039e0] [2018-05-27 12:03:02,328] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x000039e0] [2018-05-27 12:03:02,328] - TelnetServer server is running on port 34000
  INFO [0x000039e0] [2018-05-27 12:03:02,329] - ---- logger is running ----
 DEBUG [0x000039e0] [2018-05-27 12:03:02,329] - Components::process(): Request for the process of identity...
  INFO [0x000039e0] [2018-05-27 12:03:09,468] - Components::process(): Found all the components!
  INFO [0x000039e0] [2018-05-27 12:03:10,008] - ServerApp::onRegisterNewApp: uid:11544, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51275, extaddr:nonsupport, extport:0,  from 192.168.0.104:51286/0/0/0.
  INFO [0x000039e0] [2018-05-27 12:03:10,009] - Components::addComponent: reset orderLog, uid=11544!
  INFO [0x000039e0] [2018-05-27 12:03:10,010] - Components::addComponent[baseappmgr], uid=11544, componentID=5000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x000039e0] [2018-05-27 12:03:10,208] - ServerApp::onRegisterNewApp: uid:11544, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51273, extaddr:nonsupport, extport:0,  from 192.168.0.104:51287/0/0/0.
  INFO [0x000039e0] [2018-05-27 12:03:10,209] - Components::addComponent[cellapp], uid=11544, componentID=8001, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x000039e0] [2018-05-27 12:03:10,328] - ServerApp::onRegisterNewApp: uid:11544, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51276, extaddr:nonsupport, extport:0,  from 192.168.0.104:51288/0/0/0.
  INFO [0x000039e0] [2018-05-27 12:03:10,328] - Components::addComponent[cellappmgr], uid=11544, componentID=6000, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x000039e0] [2018-05-27 12:03:10,329] - ServerApp::onRegisterNewApp: uid:11544, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51272, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:51289/0/0/0.
  INFO [0x000039e0] [2018-05-27 12:03:10,330] - Components::addComponent[loginapp], uid=11544, componentID=9000, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x000039e0] [2018-05-27 12:03:11,528] - ServerApp::onRegisterNewApp: uid:11544, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51277, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:51290/0/0/0.
  INFO [0x000039e0] [2018-05-27 12:03:11,528] - Components::addComponent[baseapp], uid=11544, componentID=7001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x000039e0] [2018-05-27 12:03:11,948] - ServerApp::onRegisterNewApp: uid:11544, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51271, extaddr:nonsupport, extport:0,  from 192.168.0.104:51291/0/0/0.
  INFO [0x000039e0] [2018-05-27 12:03:11,948] - Components::addComponent[dbmgr], uid=11544, componentID=4000, globalorderid=6, grouporderid=1, totalcount=1
  INFO [0x000035b8] [2018-05-27 12:03:32,481] - 
  INFO [0x000035b8] [2018-05-27 12:03:32,482] - -----------------------------------------------------------------------------------------


  INFO [0x000035b8] [2018-05-27 12:03:32,482] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x000035b8] [2018-05-27 12:03:32,482] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x000035b8] [2018-05-27 12:03:32,482] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x000035b8] [2018-05-27 12:03:32,491] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51310 )
  INFO [0x000035b8] [2018-05-27 12:03:32,491] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:51310, SOMAXCONN=5.
  INFO [0x000035b8] [2018-05-27 12:03:32,493] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51311 )
  INFO [0x000035b8] [2018-05-27 12:03:32,493] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51311, SOMAXCONN=5.
  INFO [0x000035b8] [2018-05-27 12:03:32,496] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 11646. PID: 11604 ----
  INFO [0x000035b8] [2018-05-27 12:03:32,497] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x000035b8] [2018-05-27 12:03:32,497] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x000035b8] [2018-05-27 12:03:32,498] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x000035b8] [2018-05-27 12:03:32,626] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x000035b8] [2018-05-27 12:03:32,626] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x000035b8] [2018-05-27 12:03:32,626] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x000035b8] [2018-05-27 12:03:32,629] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x000035b8] [2018-05-27 12:03:32,630] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x000035b8] [2018-05-27 12:03:32,630] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x000035b8] [2018-05-27 12:03:32,630] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x000035b8] [2018-05-27 12:03:32,661] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x000035b8] [2018-05-27 12:03:32,696] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x000035b8] [2018-05-27 12:03:32,696] - Script::install(): KBExtra is successfully!
S_INFO [0x000035b8] [2018-05-27 12:03:32,698] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x000035b8] [2018-05-27 12:03:32,698] - TelnetServer server is running on port 34000
  INFO [0x000035b8] [2018-05-27 12:03:32,699] - ---- logger is running ----
 DEBUG [0x000035b8] [2018-05-27 12:03:32,699] - Components::process(): Request for the process of identity...
  INFO [0x000035b8] [2018-05-27 12:03:39,799] - Components::process(): Found all the components!
  INFO [0x000035b8] [2018-05-27 12:03:40,319] - ServerApp::onRegisterNewApp: uid:11646, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51309, extaddr:nonsupport, extport:0,  from 192.168.0.104:51324/0/0/0.
  INFO [0x000035b8] [2018-05-27 12:03:40,320] - Components::addComponent: reset orderLog, uid=11646!
  INFO [0x000035b8] [2018-05-27 12:03:40,320] - Components::addComponent[cellappmgr], uid=11646, componentID=6000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x000035b8] [2018-05-27 12:03:40,619] - ServerApp::onRegisterNewApp: uid:11646, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51315, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:51325/0/0/0.
  INFO [0x000035b8] [2018-05-27 12:03:40,619] - Components::addComponent[loginapp], uid=11646, componentID=9000, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x000035b8] [2018-05-27 12:03:40,620] - ServerApp::onRegisterNewApp: uid:11646, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51312, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:51326/0/0/0.
  INFO [0x000035b8] [2018-05-27 12:03:40,620] - Components::addComponent[baseapp], uid=11646, componentID=7001, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x000035b8] [2018-05-27 12:03:41,539] - ServerApp::onRegisterNewApp: uid:11646, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51316, extaddr:nonsupport, extport:0,  from 192.168.0.104:51327/0/0/0.
  INFO [0x000035b8] [2018-05-27 12:03:41,539] - Components::addComponent[baseappmgr], uid=11646, componentID=5000, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x000035b8] [2018-05-27 12:03:41,639] - ServerApp::onRegisterNewApp: uid:11646, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51313, extaddr:nonsupport, extport:0,  from 192.168.0.104:51328/0/0/0.
  INFO [0x000035b8] [2018-05-27 12:03:41,640] - Components::addComponent[cellapp], uid=11646, componentID=8001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x000035b8] [2018-05-27 12:03:42,159] - ServerApp::onRegisterNewApp: uid:11646, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51308, extaddr:nonsupport, extport:0,  from 192.168.0.104:51329/0/0/0.
  INFO [0x000035b8] [2018-05-27 12:03:42,160] - Components::addComponent[dbmgr], uid=11646, componentID=4000, globalorderid=6, grouporderid=1, totalcount=1
  INFO [0x0000221c] [2018-05-27 12:16:32,701] - 
  INFO [0x0000221c] [2018-05-27 12:16:32,702] - -----------------------------------------------------------------------------------------


  INFO [0x0000221c] [2018-05-27 12:16:32,703] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x0000221c] [2018-05-27 12:16:32,703] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x0000221c] [2018-05-27 12:16:32,703] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x0000221c] [2018-05-27 12:16:32,709] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51485 )
  INFO [0x0000221c] [2018-05-27 12:16:32,709] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:51485, SOMAXCONN=5.
  INFO [0x0000221c] [2018-05-27 12:16:32,711] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51487 )
  INFO [0x0000221c] [2018-05-27 12:16:32,711] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51487, SOMAXCONN=5.
  INFO [0x0000221c] [2018-05-27 12:16:32,717] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 14193. PID: 3048 ----
  INFO [0x0000221c] [2018-05-27 12:16:32,723] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x0000221c] [2018-05-27 12:16:32,723] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x0000221c] [2018-05-27 12:16:32,724] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x0000221c] [2018-05-27 12:16:32,858] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x0000221c] [2018-05-27 12:16:32,858] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x0000221c] [2018-05-27 12:16:32,859] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x0000221c] [2018-05-27 12:16:32,863] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x0000221c] [2018-05-27 12:16:32,864] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x0000221c] [2018-05-27 12:16:32,864] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x0000221c] [2018-05-27 12:16:32,864] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x0000221c] [2018-05-27 12:16:32,897] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x0000221c] [2018-05-27 12:16:32,930] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x0000221c] [2018-05-27 12:16:32,930] - Script::install(): KBExtra is successfully!
S_INFO [0x0000221c] [2018-05-27 12:16:32,931] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x0000221c] [2018-05-27 12:16:32,932] - TelnetServer server is running on port 34000
  INFO [0x0000221c] [2018-05-27 12:16:32,932] - ---- logger is running ----
 DEBUG [0x0000221c] [2018-05-27 12:16:32,932] - Components::process(): Request for the process of identity...
  INFO [0x0000221c] [2018-05-27 12:16:40,072] - Components::process(): Found all the components!
  INFO [0x0000221c] [2018-05-27 12:16:40,513] - ServerApp::onRegisterNewApp: uid:14193, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51483, extaddr:nonsupport, extport:0,  from 192.168.0.104:51498/0/0/0.
  INFO [0x0000221c] [2018-05-27 12:16:40,513] - Components::addComponent: reset orderLog, uid=14193!
  INFO [0x0000221c] [2018-05-27 12:16:40,514] - Components::addComponent[baseappmgr], uid=14193, componentID=5000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x0000221c] [2018-05-27 12:16:40,933] - ServerApp::onRegisterNewApp: uid:14193, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51486, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:51499/0/0/0.
  INFO [0x0000221c] [2018-05-27 12:16:40,933] - Components::addComponent[loginapp], uid=14193, componentID=9000, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x0000221c] [2018-05-27 12:16:41,233] - ServerApp::onRegisterNewApp: uid:14193, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51482, extaddr:nonsupport, extport:0,  from 192.168.0.104:51500/0/0/0.
  INFO [0x0000221c] [2018-05-27 12:16:41,234] - Components::addComponent[dbmgr], uid=14193, componentID=4000, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x0000221c] [2018-05-27 12:16:41,833] - ServerApp::onRegisterNewApp: uid:14193, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51479, extaddr:nonsupport, extport:0,  from 192.168.0.104:51501/0/0/0.
  INFO [0x0000221c] [2018-05-27 12:16:41,833] - Components::addComponent[cellapp], uid=14193, componentID=8001, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x0000221c] [2018-05-27 12:16:42,054] - ServerApp::onRegisterNewApp: uid:14193, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51484, extaddr:nonsupport, extport:0,  from 192.168.0.104:51502/0/0/0.
  INFO [0x0000221c] [2018-05-27 12:16:42,055] - Components::addComponent[cellappmgr], uid=14193, componentID=6000, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x0000221c] [2018-05-27 12:16:42,073] - ServerApp::onRegisterNewApp: uid:14193, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51480, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:51503/0/0/0.
  INFO [0x0000221c] [2018-05-27 12:16:42,073] - Components::addComponent[baseapp], uid=14193, componentID=7001, globalorderid=6, grouporderid=1, totalcount=1
  INFO [0x00001688] [2018-05-27 12:42:19,042] - 
  INFO [0x00001688] [2018-05-27 12:42:19,042] - -----------------------------------------------------------------------------------------


  INFO [0x00001688] [2018-05-27 12:42:19,043] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x00001688] [2018-05-27 12:42:19,043] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x00001688] [2018-05-27 12:42:19,043] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x00001688] [2018-05-27 12:42:19,064] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51757 )
  INFO [0x00001688] [2018-05-27 12:42:19,064] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:51757, SOMAXCONN=5.
  INFO [0x00001688] [2018-05-27 12:42:19,077] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51759 )
  INFO [0x00001688] [2018-05-27 12:42:19,077] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51759, SOMAXCONN=5.
  INFO [0x00001688] [2018-05-27 12:42:19,080] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 19241. PID: 14192 ----
  INFO [0x00001688] [2018-05-27 12:42:19,086] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x00001688] [2018-05-27 12:42:19,086] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x00001688] [2018-05-27 12:42:19,087] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x00001688] [2018-05-27 12:42:19,219] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x00001688] [2018-05-27 12:42:19,219] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x00001688] [2018-05-27 12:42:19,219] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x00001688] [2018-05-27 12:42:19,223] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x00001688] [2018-05-27 12:42:19,223] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x00001688] [2018-05-27 12:42:19,223] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x00001688] [2018-05-27 12:42:19,224] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x00001688] [2018-05-27 12:42:19,257] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x00001688] [2018-05-27 12:42:19,297] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x00001688] [2018-05-27 12:42:19,297] - Script::install(): KBExtra is successfully!
S_INFO [0x00001688] [2018-05-27 12:42:19,299] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x00001688] [2018-05-27 12:42:19,299] - TelnetServer server is running on port 34000
  INFO [0x00001688] [2018-05-27 12:42:19,299] - ---- logger is running ----
 DEBUG [0x00001688] [2018-05-27 12:42:19,300] - Components::process(): Request for the process of identity...
  INFO [0x00001688] [2018-05-27 12:42:26,419] - Components::process(): Found all the components!
  INFO [0x00001688] [2018-05-27 12:42:26,979] - ServerApp::onRegisterNewApp: uid:19241, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51760, extaddr:nonsupport, extport:0,  from 192.168.0.104:51771/0/0/0.
  INFO [0x00001688] [2018-05-27 12:42:26,979] - Components::addComponent: reset orderLog, uid=19241!
  INFO [0x00001688] [2018-05-27 12:42:26,979] - Components::addComponent[cellappmgr], uid=19241, componentID=6000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x00001688] [2018-05-27 12:42:27,079] - ServerApp::onRegisterNewApp: uid:19241, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51761, extaddr:nonsupport, extport:0,  from 192.168.0.104:51772/0/0/0.
  INFO [0x00001688] [2018-05-27 12:42:27,079] - Components::addComponent[cellapp], uid=19241, componentID=8001, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x00001688] [2018-05-27 12:42:28,079] - ServerApp::onRegisterNewApp: uid:19241, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51756, extaddr:nonsupport, extport:0,  from 192.168.0.104:51773/0/0/0.
  INFO [0x00001688] [2018-05-27 12:42:28,080] - Components::addComponent[baseappmgr], uid=19241, componentID=5000, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x00001688] [2018-05-27 12:42:28,499] - ServerApp::onRegisterNewApp: uid:19241, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51762, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:51774/0/0/0.
  INFO [0x00001688] [2018-05-27 12:42:28,499] - Components::addComponent[loginapp], uid=19241, componentID=9000, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x00001688] [2018-05-27 12:42:28,500] - ServerApp::onRegisterNewApp: uid:19241, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51763, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:51775/0/0/0.
  INFO [0x00001688] [2018-05-27 12:42:28,500] - Components::addComponent[baseapp], uid=19241, componentID=7001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x00001688] [2018-05-27 12:42:28,799] - ServerApp::onRegisterNewApp: uid:19241, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51758, extaddr:nonsupport, extport:0,  from 192.168.0.104:51776/0/0/0.
  INFO [0x00001688] [2018-05-27 12:42:28,799] - Components::addComponent[dbmgr], uid=19241, componentID=4000, globalorderid=6, grouporderid=1, totalcount=1
  INFO [0x000037bc] [2018-05-27 12:47:29,515] - 
  INFO [0x000037bc] [2018-05-27 12:47:29,515] - -----------------------------------------------------------------------------------------


  INFO [0x000037bc] [2018-05-27 12:47:29,516] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x000037bc] [2018-05-27 12:47:29,516] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x000037bc] [2018-05-27 12:47:29,516] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x000037bc] [2018-05-27 12:47:29,520] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51849 )
  INFO [0x000037bc] [2018-05-27 12:47:29,520] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:51849, SOMAXCONN=5.
  INFO [0x000037bc] [2018-05-27 12:47:29,522] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51850 )
  INFO [0x000037bc] [2018-05-27 12:47:29,522] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51850, SOMAXCONN=5.
  INFO [0x000037bc] [2018-05-27 12:47:29,527] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 20257. PID: 13668 ----
  INFO [0x000037bc] [2018-05-27 12:47:29,527] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x000037bc] [2018-05-27 12:47:29,527] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x000037bc] [2018-05-27 12:47:29,527] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x000037bc] [2018-05-27 12:47:29,664] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x000037bc] [2018-05-27 12:47:29,665] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x000037bc] [2018-05-27 12:47:29,666] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x000037bc] [2018-05-27 12:47:29,670] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x000037bc] [2018-05-27 12:47:29,670] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x000037bc] [2018-05-27 12:47:29,671] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x000037bc] [2018-05-27 12:47:29,671] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x000037bc] [2018-05-27 12:47:29,709] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x000037bc] [2018-05-27 12:47:29,739] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x000037bc] [2018-05-27 12:47:29,739] - Script::install(): KBExtra is successfully!
S_INFO [0x000037bc] [2018-05-27 12:47:29,742] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x000037bc] [2018-05-27 12:47:29,742] - TelnetServer server is running on port 34000
  INFO [0x000037bc] [2018-05-27 12:47:29,743] - ---- logger is running ----
 DEBUG [0x000037bc] [2018-05-27 12:47:29,743] - Components::process(): Request for the process of identity...
  INFO [0x000037bc] [2018-05-27 12:47:36,863] - Components::process(): Found all the components!
  INFO [0x000037bc] [2018-05-27 12:47:37,323] - ServerApp::onRegisterNewApp: uid:20257, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51846, extaddr:nonsupport, extport:0,  from 192.168.0.104:51858/0/0/0.
  INFO [0x000037bc] [2018-05-27 12:47:37,323] - Components::addComponent: reset orderLog, uid=20257!
  INFO [0x000037bc] [2018-05-27 12:47:37,324] - Components::addComponent[baseappmgr], uid=20257, componentID=5000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x000037bc] [2018-05-27 12:47:38,623] - ServerApp::onRegisterNewApp: uid:20257, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51848, extaddr:nonsupport, extport:0,  from 192.168.0.104:51859/0/0/0.
  INFO [0x000037bc] [2018-05-27 12:47:38,624] - Components::addComponent[cellappmgr], uid=20257, componentID=6000, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x000037bc] [2018-05-27 12:47:38,823] - ServerApp::onRegisterNewApp: uid:20257, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51847, extaddr:nonsupport, extport:0,  from 192.168.0.104:51860/0/0/0.
  INFO [0x000037bc] [2018-05-27 12:47:38,823] - Components::addComponent[cellapp], uid=20257, componentID=8001, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x000037bc] [2018-05-27 12:47:38,923] - ServerApp::onRegisterNewApp: uid:20257, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51845, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:51861/0/0/0.
  INFO [0x000037bc] [2018-05-27 12:47:38,923] - Components::addComponent[loginapp], uid=20257, componentID=9000, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x000037bc] [2018-05-27 12:47:39,343] - ServerApp::onRegisterNewApp: uid:20257, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51843, extaddr:nonsupport, extport:0,  from 192.168.0.104:51862/0/0/0.
  INFO [0x000037bc] [2018-05-27 12:47:39,343] - Components::addComponent[dbmgr], uid=20257, componentID=4000, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x000037bc] [2018-05-27 12:47:39,381] - ServerApp::onRegisterNewApp: uid:20257, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51844, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:51863/0/0/0.
  INFO [0x000037bc] [2018-05-27 12:47:39,381] - Components::addComponent[baseapp], uid=20257, componentID=7001, globalorderid=6, grouporderid=1, totalcount=1
  INFO [0x00003e8c] [2018-05-27 12:52:44,516] - 
  INFO [0x00003e8c] [2018-05-27 12:52:44,521] - -----------------------------------------------------------------------------------------


  INFO [0x00003e8c] [2018-05-27 12:52:44,522] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x00003e8c] [2018-05-27 12:52:44,522] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x00003e8c] [2018-05-27 12:52:44,522] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x00003e8c] [2018-05-27 12:52:44,525] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51906 )
  INFO [0x00003e8c] [2018-05-27 12:52:44,526] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:51906, SOMAXCONN=5.
  INFO [0x00003e8c] [2018-05-27 12:52:44,527] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51907 )
  INFO [0x00003e8c] [2018-05-27 12:52:44,527] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51907, SOMAXCONN=5.
  INFO [0x00003e8c] [2018-05-27 12:52:44,530] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 21286. PID: 13580 ----
  INFO [0x00003e8c] [2018-05-27 12:52:44,531] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x00003e8c] [2018-05-27 12:52:44,532] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x00003e8c] [2018-05-27 12:52:44,532] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x00003e8c] [2018-05-27 12:52:44,667] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x00003e8c] [2018-05-27 12:52:44,667] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x00003e8c] [2018-05-27 12:52:44,667] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x00003e8c] [2018-05-27 12:52:44,671] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x00003e8c] [2018-05-27 12:52:44,671] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x00003e8c] [2018-05-27 12:52:44,671] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x00003e8c] [2018-05-27 12:52:44,672] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x00003e8c] [2018-05-27 12:52:44,710] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x00003e8c] [2018-05-27 12:52:44,745] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x00003e8c] [2018-05-27 12:52:44,745] - Script::install(): KBExtra is successfully!
S_INFO [0x00003e8c] [2018-05-27 12:52:44,747] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x00003e8c] [2018-05-27 12:52:44,748] - TelnetServer server is running on port 34000
  INFO [0x00003e8c] [2018-05-27 12:52:44,748] - ---- logger is running ----
 DEBUG [0x00003e8c] [2018-05-27 12:52:44,748] - Components::process(): Request for the process of identity...
  INFO [0x00003e8c] [2018-05-27 12:52:51,829] - Components::process(): Found all the components!
  INFO [0x00003e8c] [2018-05-27 12:52:52,389] - ServerApp::onRegisterNewApp: uid:21286, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51904, extaddr:nonsupport, extport:0,  from 192.168.0.104:51918/0/0/0.
  INFO [0x00003e8c] [2018-05-27 12:52:52,390] - Components::addComponent: reset orderLog, uid=21286!
  INFO [0x00003e8c] [2018-05-27 12:52:52,390] - Components::addComponent[baseappmgr], uid=21286, componentID=5000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x00003e8c] [2018-05-27 12:52:52,789] - ServerApp::onRegisterNewApp: uid:21286, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51910, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:51919/0/0/0.
  INFO [0x00003e8c] [2018-05-27 12:52:52,790] - Components::addComponent[loginapp], uid=21286, componentID=9000, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x00003e8c] [2018-05-27 12:52:52,989] - ServerApp::onRegisterNewApp: uid:21286, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51905, extaddr:nonsupport, extport:0,  from 192.168.0.104:51920/0/0/0.
  INFO [0x00003e8c] [2018-05-27 12:52:52,990] - Components::addComponent[dbmgr], uid=21286, componentID=4000, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x00003e8c] [2018-05-27 12:52:53,529] - ServerApp::onRegisterNewApp: uid:21286, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51902, extaddr:nonsupport, extport:0,  from 192.168.0.104:51921/0/0/0.
  INFO [0x00003e8c] [2018-05-27 12:52:53,529] - Components::addComponent[cellappmgr], uid=21286, componentID=6000, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x00003e8c] [2018-05-27 12:52:53,709] - ServerApp::onRegisterNewApp: uid:21286, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51908, extaddr:nonsupport, extport:0,  from 192.168.0.104:51922/0/0/0.
  INFO [0x00003e8c] [2018-05-27 12:52:53,709] - Components::addComponent[cellapp], uid=21286, componentID=8001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x00003e8c] [2018-05-27 12:52:54,009] - ServerApp::onRegisterNewApp: uid:21286, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:51909, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:51923/0/0/0.
  INFO [0x00003e8c] [2018-05-27 12:52:54,010] - Components::addComponent[baseapp], uid=21286, componentID=7001, globalorderid=6, grouporderid=1, totalcount=1
  INFO [0x00001afc] [2018-05-27 13:02:38,733] - 
  INFO [0x00001afc] [2018-05-27 13:02:38,733] - -----------------------------------------------------------------------------------------


  INFO [0x00001afc] [2018-05-27 13:02:38,733] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x00001afc] [2018-05-27 13:02:38,734] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x00001afc] [2018-05-27 13:02:38,734] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x00001afc] [2018-05-27 13:02:38,742] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52021 )
  INFO [0x00001afc] [2018-05-27 13:02:38,742] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:52021, SOMAXCONN=5.
  INFO [0x00001afc] [2018-05-27 13:02:38,743] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52023 )
  INFO [0x00001afc] [2018-05-27 13:02:38,743] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:52023, SOMAXCONN=5.
  INFO [0x00001afc] [2018-05-27 13:02:38,747] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 23225. PID: 15340 ----
  INFO [0x00001afc] [2018-05-27 13:02:38,748] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x00001afc] [2018-05-27 13:02:38,750] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x00001afc] [2018-05-27 13:02:38,750] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x00001afc] [2018-05-27 13:02:38,885] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x00001afc] [2018-05-27 13:02:38,886] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x00001afc] [2018-05-27 13:02:38,886] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x00001afc] [2018-05-27 13:02:38,889] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x00001afc] [2018-05-27 13:02:38,889] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x00001afc] [2018-05-27 13:02:38,889] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x00001afc] [2018-05-27 13:02:38,890] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x00001afc] [2018-05-27 13:02:38,927] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x00001afc] [2018-05-27 13:02:38,966] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x00001afc] [2018-05-27 13:02:38,966] - Script::install(): KBExtra is successfully!
S_INFO [0x00001afc] [2018-05-27 13:02:38,968] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x00001afc] [2018-05-27 13:02:38,968] - TelnetServer server is running on port 34000
  INFO [0x00001afc] [2018-05-27 13:02:38,969] - ---- logger is running ----
 DEBUG [0x00001afc] [2018-05-27 13:02:38,969] - Components::process(): Request for the process of identity...
  INFO [0x00001afc] [2018-05-27 13:02:46,129] - Components::process(): Found all the components!
  INFO [0x00001afc] [2018-05-27 13:02:46,629] - ServerApp::onRegisterNewApp: uid:23225, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:52025, extaddr:nonsupport, extport:0,  from 192.168.0.104:52037/0/0/0.
  INFO [0x00001afc] [2018-05-27 13:02:46,630] - Components::addComponent: reset orderLog, uid=23225!
  INFO [0x00001afc] [2018-05-27 13:02:46,630] - Components::addComponent[baseappmgr], uid=23225, componentID=5000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x00001afc] [2018-05-27 13:02:46,649] - ServerApp::onRegisterNewApp: uid:23225, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:52027, extaddr:nonsupport, extport:0,  from 192.168.0.104:52038/0/0/0.
  INFO [0x00001afc] [2018-05-27 13:02:46,650] - Components::addComponent[cellappmgr], uid=23225, componentID=6000, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x00001afc] [2018-05-27 13:02:46,749] - ServerApp::onRegisterNewApp: uid:23225, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:52026, extaddr:nonsupport, extport:0,  from 192.168.0.104:52039/0/0/0.
  INFO [0x00001afc] [2018-05-27 13:02:46,750] - Components::addComponent[cellapp], uid=23225, componentID=8001, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x00001afc] [2018-05-27 13:02:48,169] - ServerApp::onRegisterNewApp: uid:23225, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:52029, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:52040/0/0/0.
  INFO [0x00001afc] [2018-05-27 13:02:48,170] - Components::addComponent[loginapp], uid=23225, componentID=9000, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x00001afc] [2018-05-27 13:02:48,171] - ServerApp::onRegisterNewApp: uid:23225, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:52028, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:52041/0/0/0.
  INFO [0x00001afc] [2018-05-27 13:02:48,172] - Components::addComponent[baseapp], uid=23225, componentID=7001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x00001afc] [2018-05-27 13:02:48,389] - ServerApp::onRegisterNewApp: uid:23225, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:52024, extaddr:nonsupport, extport:0,  from 192.168.0.104:52042/0/0/0.
  INFO [0x00001afc] [2018-05-27 13:02:48,389] - Components::addComponent[dbmgr], uid=23225, componentID=4000, globalorderid=6, grouporderid=1, totalcount=1
  INFO [0x000037a8] [2018-05-27 13:08:34,220] - 
  INFO [0x000037a8] [2018-05-27 13:08:34,220] - -----------------------------------------------------------------------------------------


  INFO [0x000037a8] [2018-05-27 13:08:34,221] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x000037a8] [2018-05-27 13:08:34,221] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x000037a8] [2018-05-27 13:08:34,221] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x000037a8] [2018-05-27 13:08:34,236] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52289 )
  INFO [0x000037a8] [2018-05-27 13:08:34,236] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:52289, SOMAXCONN=5.
  INFO [0x000037a8] [2018-05-27 13:08:34,238] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52292 )
  INFO [0x000037a8] [2018-05-27 13:08:34,238] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:52292, SOMAXCONN=5.
  INFO [0x000037a8] [2018-05-27 13:08:34,244] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 24385. PID: 11392 ----
  INFO [0x000037a8] [2018-05-27 13:08:34,244] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x000037a8] [2018-05-27 13:08:34,244] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x000037a8] [2018-05-27 13:08:34,245] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x000037a8] [2018-05-27 13:08:34,386] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x000037a8] [2018-05-27 13:08:34,386] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x000037a8] [2018-05-27 13:08:34,386] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x000037a8] [2018-05-27 13:08:34,389] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG [0x000037a8] [2018-05-27 13:08:34,389] - Script::install_py_dlls(): PyInit_select
 DEBUG [0x000037a8] [2018-05-27 13:08:34,390] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG [0x000037a8] [2018-05-27 13:08:34,390] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG [0x000037a8] [2018-05-27 13:08:34,420] - Script::install_py_dlls(): PyInit_unicodedata
  INFO [0x000037a8] [2018-05-27 13:08:34,448] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO [0x000037a8] [2018-05-27 13:08:34,448] - Script::install(): KBExtra is successfully!
S_INFO [0x000037a8] [2018-05-27 13:08:34,450] - onLoggerAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO [0x000037a8] [2018-05-27 13:08:34,450] - TelnetServer server is running on port 34000
  INFO [0x000037a8] [2018-05-27 13:08:34,451] - ---- logger is running ----
 DEBUG [0x000037a8] [2018-05-27 13:08:34,451] - Components::process(): Request for the process of identity...
  INFO [0x000037a8] [2018-05-27 13:08:41,610] - Components::process(): Found all the components!
  INFO [0x000037a8] [2018-05-27 13:08:42,090] - ServerApp::onRegisterNewApp: uid:24385, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:52291, extaddr:nonsupport, extport:0,  from 192.168.0.104:52300/0/0/0.
  INFO [0x000037a8] [2018-05-27 13:08:42,090] - Components::addComponent: reset orderLog, uid=24385!
  INFO [0x000037a8] [2018-05-27 13:08:42,090] - Components::addComponent[baseappmgr], uid=24385, componentID=5000, globalorderid=1, grouporderid=1, totalcount=1
  INFO [0x000037a8] [2018-05-27 13:08:42,091] - ServerApp::onRegisterNewApp: uid:24385, username:, componentType:cellappmgr, componentID:6000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:52286, extaddr:nonsupport, extport:0,  from 192.168.0.104:52301/0/0/0.
  INFO [0x000037a8] [2018-05-27 13:08:42,091] - Components::addComponent[cellappmgr], uid=24385, componentID=6000, globalorderid=2, grouporderid=1, totalcount=1
  INFO [0x000037a8] [2018-05-27 13:08:43,490] - ServerApp::onRegisterNewApp: uid:24385, username:, componentType:cellapp, componentID:8001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:52290, extaddr:nonsupport, extport:0,  from 192.168.0.104:52302/0/0/0.
  INFO [0x000037a8] [2018-05-27 13:08:43,490] - Components::addComponent[cellapp], uid=24385, componentID=8001, globalorderid=3, grouporderid=1, totalcount=1
  INFO [0x000037a8] [2018-05-27 13:08:43,710] - ServerApp::onRegisterNewApp: uid:24385, username:, componentType:loginapp, componentID:9000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:52288, extaddr:192.168.0.104, extport:20013,  from 192.168.0.104:52303/0/0/0.
  INFO [0x000037a8] [2018-05-27 13:08:43,711] - Components::addComponent[loginapp], uid=24385, componentID=9000, globalorderid=4, grouporderid=1, totalcount=1
  INFO [0x000037a8] [2018-05-27 13:08:44,010] - ServerApp::onRegisterNewApp: uid:24385, username:, componentType:baseapp, componentID:7001, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:52284, extaddr:192.168.0.104, extport:20015,  from 192.168.0.104:52304/0/0/0.
  INFO [0x000037a8] [2018-05-27 13:08:44,011] - Components::addComponent[baseapp], uid=24385, componentID=7001, globalorderid=5, grouporderid=1, totalcount=1
  INFO [0x000037a8] [2018-05-27 13:08:44,230] - ServerApp::onRegisterNewApp: uid:24385, username:, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:52287, extaddr:nonsupport, extport:0,  from 192.168.0.104:52305/0/0/0.
  INFO [0x000037a8] [2018-05-27 13:08:44,231] - Components::addComponent[dbmgr], uid=24385, componentID=4000, globalorderid=6, grouporderid=1, totalcount=1
  INFO [0x00002394] [2018-05-27 13:10:36,168] - 
  INFO [0x00002394] [2018-05-27 13:10:36,169] - -----------------------------------------------------------------------------------------


  INFO [0x00002394] [2018-05-27 13:10:36,170] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO [0x00002394] [2018-05-27 13:10:36,170] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO [0x00002394] [2018-05-27 13:10:36,170] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO [0x00002394] [2018-05-27 13:10:36,176] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52339 )
  INFO [0x00002394] [2018-05-27 13:10:36,176] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:52339, SOMAXCONN=5.
  INFO [0x00002394] [2018-05-27 13:10:36,177] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52340 )
  INFO [0x00002394] [2018-05-27 13:10:36,177] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:52340, SOMAXCONN=5.
  INFO [0x00002394] [2018-05-27 13:10:36,185] - ---- logger Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: A3DC7D56ADF83CF3542C1D62D3A135C3. Config: Debug X86. Built: 15:52:51 Apr 29 2018. AppID: 2000. UID: 24783. PID: 1528 ----
  INFO [0x00002394] [2018-05-27 13:10:36,186] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO [0x00002394] [2018-05-27 13:10:36,186] - ThreadPool::createThreadPool: creating  threadpool...
  INFO [0x00002394] [2018-05-27 13:10:36,187] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG [0x00002394] [2018-05-27 13:10:36,317] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG [0x00002394] [2018-05-27 13:10:36,317] - Script::install_py_dlls(): PyInit__socket
 DEBUG [0x00002394] [2018-05-27 13:10:36,318] - Script::install_py_dlls(): PyInit__ssl
 DEBUG [0x00002394] [2018-05-27 13:10:36,321] - Script::install_py_dlls(): PyInit__hashlib
